# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160215_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.CharField(default='New Member', max_length=40),
        ),
    ]
