# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('projects', '0002_auto_20160216_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_team', to='teams.Team'),
        ),
    ]
