# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160215_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinfo',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_social', to='users.Account'),
        ),
    ]
