# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160218_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
