# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160310_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
